### ISSUE TITLE
Can I load extension templates via the core TemplateManager

### ISSUE THREAD

**Issue by barrykooij** [ibericode/wp-knowledge-base#17]
Building an extension and would like to load a template file in it. I want to use the core TemplateManager so we all use the same template class. Template should be overridable via theme and I would like to set available variables per template file include.

**Comment by dannyvankooten** [comment]
Hey @barrykooij,

I've deleted the entire "template" stuff in 88148249aae8054a95c69f29bfa0d2dff5bf4543 as it was quite cumbersome and not really compatible with most themes out there. Would love to pick it up again and do it right though.
