### ISSUE TITLE
List of possible shortcodes

### ISSUE THREAD

**Issue by Kail0** [ibericode/wp-knowledge-base#52]
Hi there,
I don't want to sound rude, neither stupid, but is there a whole list of shortcodes? 

I was able to separated few via "issue desk", but how about other one? May ask for them?

thank you for answer

**Comment by dannyvankooten** [comment]
Hi @Kail0 ,

Please have a look at [the repository's README file](https://github.com/ibericode/wp-knowledge-base), there's a heading called "Functions & Shortcodes" which should be of help here. I realise this project's lacking a ton of documentation, it's something we used internally which shouldn't have gotten this much attention this soon. I'll be giving it some much deserved love soon. :)

Cheers!

**Comment by Kail0** [comment]
Ahh, I see. That's ok, @dannyvankooten (:

Well, it might have lack of documentation, but it's really well done  -without tones of "crappy" function like the one I've found in wordpress repo.

Light, easy to use for regular user.. (: looking forward for updates.
